<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bitforcev2" nsURI="http://bitforcev2/1.0" nsPrefix="bitforcev2">
  <eClassifiers xsi:type="ecore:EClass" name="BFLCmd" eSuperTypes="../../net.sf.xqz.engine/model/cmd.ecore#//Cmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//BFLCmdKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BFLCmdKind">
    <eLiterals name="ZGX"/>
    <eLiterals name="ZCX" value="1"/>
    <eLiterals name="ZMX" value="2"/>
    <eLiterals name="ZTX" value="3"/>
    <eLiterals name="ZLX" value="4"/>
    <eLiterals name="ZJX" value="5"/>
    <eLiterals name="ZFX" value="6"/>
    <eLiterals name="ZDX" value="7"/>
    <eLiterals name="ZPX" value="8"/>
    <eLiterals name="ZNX" value="9"/>
    <eLiterals name="ZOX" value="10"/>
    <eLiterals name="ZQX" value="11"/>
    <eLiterals name="OK" value="12"/>
    <eLiterals name="KO" value="13"/>
    <eLiterals name="NONE" value="14"/>
    <eLiterals name="ZDXFullRange" value="15"/>
    <eLiterals name="ZPXCustomRange" value="16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZGX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZCX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="device" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firmware" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engines" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobsQueue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultsQueue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xlinkMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xlinkStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="devicesInChain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZMX" eSuperTypes="#//BFLCmd"/>
  <eClassifiers xsi:type="ecore:EClass" name="ZTX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="v3_3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="v1_0" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vccMain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZLX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZJX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firmwareVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZFX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultKind" eType="#//JobResultsKnd"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonces" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZDXFullRangeJob" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="midState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZPXCustomRangeJob" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="midState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonceBegin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonceEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZNX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="midState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZOX" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lines" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZQX" eSuperTypes="#//BFLCmd"/>
  <eClassifiers xsi:type="ecore:EEnum" name="JobResultsKnd">
    <eLiterals name="BUSY"/>
    <eLiterals name="IDLE" value="1"/>
    <eLiterals name="NO_ONCE" value="2"/>
    <eLiterals name="NONCE_FOUND" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OK" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msg" eType="#//MSG"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KO" eSuperTypes="#//BFLCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="#//ERR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZDX" eSuperTypes="#//BFLCmd"/>
  <eClassifiers xsi:type="ecore:EClass" name="ZPX" eSuperTypes="#//BFLCmd"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ERR">
    <eLiterals name="QUEUE_FULL"/>
    <eLiterals name="TIMEOUT" value="1"/>
    <eLiterals name="SIGNATURE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MSG">
    <eLiterals name="QUEUED"/>
  </eClassifiers>
</ecore:EPackage>
