<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bitcoinrpc" nsURI="http://bitcoinrpc/1.0" nsPrefix="bitcoinrpc">
  <eClassifiers xsi:type="ecore:EClass" name="BitcoinNode" eSuperTypes="../../net.sf.xqz.engine/model/engine.ecore#//IConnectedUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="info" eType="#//BtcInfo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="btcAddr" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inetAddr" eType="ecore:EClass ../../net.sf.smbt.xcp/model/xcp.ecore#//XCPAddress"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BtcInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="balance" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errors" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paytxfee" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connected" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testnet" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulty" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocks" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>
